### ISSUE TITLE
exception raised on windows

### ISSUE THREAD

**Issue by morngrar** [morngrar/spendtime#7]
heres the traceback:

`
Traceback (most recent call last):
  File "C:\Users\svebjo\AppData\Local\Programs\Python\Python36-32\Scripts\spendtime-script.py", line 11, in <module>
    load_entry_point('spendtime==0.1.0', 'console_scripts', 'spendtime')()
  File "c:\users\svebjo\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 560, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\svebjo\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2648, in load_entry_point
    return ep.load()
  File "c:\users\svebjo\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2302, in load
    return self.resolve()
  File "c:\users\svebjo\appdata\local\programs\python\python36-32\lib\site-packages\pkg_resources\__init__.py", line 2308, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\svebjo\appdata\local\programs\python\python36-32\lib\site-packages\spendtime\__init__.py", line 1, in <module>
    from .spendtime import main
  File "c:\users\svebjo\appdata\local\programs\python\python36-32\lib\site-packages\spendtime\spendtime.py", line 157
    global COPYRIGHT_SHOWN
    ^
SyntaxError: name 'COPYRIGHT_SHOWN' is used prior to global declaration
`

**Comment by morngrar** [comment]
Fixed in repo. Creating new issue to update pypi package.
